import Link from 'next/link'
import styles from './about.module.css'

export default function About() {
  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <Link href="/" className={styles.back}>← Back to RiderFit</Link>
        <h1>About RiderFit</h1>
        <p>RiderFit is an AI-powered motorcycle gear advisor. We help riders find the right helmet, jacket, gloves, boots, and pants — matched to their riding style, experience level, climate, and budget.</p>
        <p>Our recommendations are generated by AI and are intended as a starting point. Always verify safety ratings and fit before purchasing any protective gear.</p>
        <h2>How it works</h2>
        <p>You fill in a short profile about how you ride. Our AI analyzes your inputs and generates a personalised full gear setup recommendation with specific product suggestions and links to European retailers.</p>
        <h2>Affiliate disclosure</h2>
        <p>RiderFit uses affiliate links. When you click a product link and make a purchase, we may earn a small commission at no extra cost to you. This helps keep RiderFit free to use.</p>
      </div>
    </main>
  )
}
